version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
environment:
  github_token: 'secure: TaDEavUfTj6EgwcO7y5njQVS5Z9bBU/fVFuSApo5XEO6FSBT5UzJQmyJjbhIFDZb'
  myget_token: 'secure: 9Z+KYPk2hI7hg9kYLv/N13fvoqcYCP96isNUkRrKu0v87cw85H62oe/DCwpqvBXF'
  sonar_token: 'secure: n/AY/tcvsDCo4fOmDjYRe2xprYqjV6rKeAmmC2YbkFfCHAfiANDOlblWYUVhbkQu'
install:
- choco install gitversion.portable -y
- choco install "msbuild-sonarqube-runner" -y
- cmd: nuget sources add -Name EPiServerFeed -Source http://nuget.episerver.com/feed/packages.svc/
before_build:
- cmd: nuget restore
- ps: gitversion /l console /output buildserver /updateAssemblyInfo
build_script:
  - ps: MSBuild.SonarQube.Runner.exe begin /k:"jstemerdink:EPi.Libraries.QnaMaker" /n:"EPi.Libraries.QnaMaker" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.organization=jstemerdink-github" /d:"sonar.login=$env:sonar_token"
  - msbuild "EPi.Libraries.QnaMaker.sln"
  - ps: MSBuild.SonarQube.Runner.exe end /d:"sonar.login=$env:sonar_token"
after_build:
- cmd: nuget pack EPi.Libraries.QnaMaker\EPi.Libraries.QnaMaker.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
- cmd: appveyor PushArtifact "EPi.Libraries.QnaMaker.%GitVersion_NuGetVersion%.nupkg"
- 7z a EPi.Libraries.QnaMaker.%GitVersion_NuGetVersion%.zip %APPVEYOR_BUILD_FOLDER%\EPi.Libraries.QnaMaker\bin\Release\EPi.Libraries.QnaMaker.dll
- cmd: appveyor PushArtifact "EPi.Libraries.QnaMaker.%GitVersion_NuGetVersion%.zip"

- cmd: nuget pack EPi.Libraries.QnaMaker.ContentArea\EPi.Libraries.QnaMaker.ContentArea.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
- cmd: appveyor PushArtifact "EPi.Libraries.QnaMaker.ContentArea.%GitVersion_NuGetVersion%.nupkg"
- 7z a EPi.Libraries.QnaMaker.ContentArea.%GitVersion_NuGetVersion%.zip %APPVEYOR_BUILD_FOLDER%\EPi.Libraries.QnaMaker.ContentArea\bin\Release\EPi.Libraries.QnaMaker.ContentArea.dll
- cmd: appveyor PushArtifact "EPi.Libraries.QnaMaker.ContentArea.%GitVersion_NuGetVersion%.zip"
before_package:
- ps: >-
    Write-Host -NoNewline "Installing NuGet 3.3.0..."

    if (Test-Path 'C:\Tools\NuGet3') { $nugetDir = 'C:\Tools\NuGet3' } else { $nugetDir = 'C:\Tools\NuGet' }
deploy:
- provider: NuGet
  server: https://www.myget.org/F/epi-libraries/api/v2/package
  api_key:
    secure: 9Z+KYPk2hI7hg9kYLv/N13fvoqcYCP96isNUkRrKu0v87cw85H62oe/DCwpqvBXF
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: develop             # release from develop branch only
    #appveyor_repo_tag: true     # deploy on tag push only
- provider: GitHub
  auth_token:
    secure: TaDEavUfTj6EgwcO7y5njQVS5Z9bBU/fVFuSApo5XEO6FSBT5UzJQmyJjbhIFDZb
  artifact: /.*\.zip/
  on:
    branch: master              # release from master branch only
    #appveyor_repo_tag: true     # deploy on tag push only